import Head from "next/head";
import Link from "next/link";
import React, { useEffect, useState, useContext } from "react";
import { Store } from "../utils/Store";
export default function Layout({ title, children }) {
  const { state, dispatch } = useContext(Store);

  const { cart } = state;

  const [carItemCount, setCartItemCount] = useState();

  useEffect(() => {
    setCartItemCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, []);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>{title ? title + " amazona" : "amazona"}</title>
      </Head>
      <div className="flex min-h-screen flex-col justify-between font-bold">
        <header>
          <nav className="flex justify-between h-12 items-center shadow-md px-4">
            <Link href="/" legacyBehavior>
              <a className="text-lg font-bold">amazona</a>
            </Link>
            <div>
              <Link href="/cart" legacyBehavior>
                <a className="px-2">
                  Cart
                  {carItemCount > 0 && (
                    <span className="ml-1 px-2 py-1 rounded-full bg-red-600 text-sm font-bold text-white">
                      {carItemCount}
                    </span>
                  )}
                </a>
              </Link>
              <Link href="/" legacyBehavior>
                <a className="px-2">Login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center items-center shadow-inner h-10">
          Copyright @ 2022 Amazona
        </footer>
      </div>
    </>
  );
}
