export const data = {
  products: [
    {
      name: "Free shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brank: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A Popular T-Shirt",
    },
    {
      name: "Slim shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 70,
      brank: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A Popular T-Shirt",
    },
    {
      name: "Big shirt",
      slug: "big-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 70,
      brank: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A Popular T-Shirt",
    },
    {
      name: "Fancy shirt",
      slug: "fancy-shirt",
      category: "Shirts",
      image: "/images/pants1.jpg",
      price: 70,
      brank: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A Popular T-Shirt",
    },
    {
      name: "New shirt",
      slug: "new-shirt",
      category: "Shirts",
      image: "/images/pants2.jpg",
      price: 70,
      brank: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A Popular T-Shirt",
    },
  ],
};
