import bcrypt from "bcryptjs/dist/bcrypt";

export const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Shirt 1",
      slug: "shirt-1",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brank: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A Popular T-Shirt",
    },
    {
      name: "Shirt 2",
      slug: "shirt-2",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 70,
      brank: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A Popular T-Shirt",
    },
    {
      name: "Shirt 3",
      slug: "shirt-3",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 70,
      brank: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A Popular T-Shirt",
    },
    {
      name: "Shirt 4",
      slug: "shirt-4",
      category: "Shirts",
      image: "/images/pants1.jpg",
      price: 70,
      brank: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A Popular T-Shirt",
    },
    {
      name: "Shirt 6",
      slug: "shirt-5",
      category: "Shirts",
      image: "/images/pants2.jpg",
      price: 70,
      brank: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A Popular T-Shirt",
    },
  ],
};
